### ISSUE TITLE
Add CLA bot?

### ISSUE THREAD

**Issue by kennethormandy** [googlefonts/japanese#11]
Should we get @googlebot running on this repository?

<img width="785" alt="screenshot 2016-10-20 15 16 28" src="https://cloud.githubusercontent.com/assets/1581276/19579993/430ba99c-96d8-11e6-8e30-36b6c8e9bfb9.png">

It would make it easier for me to know I can merge things, and also resolve https://github.com/googlefonts/japanese/pull/5#issuecomment-255019166 which I don’t know how to check.

**Comment by davelab6** [comment]
Done
