### ISSUE TITLE
Graduate some families from Early Access

### ISSUE THREAD

**Issue by davelab6** [googlefonts/japanese#16]
I started a branch [davelab6-no-ea](https://github.com/googlefonts/japanese/tree/davelab6-no-ea) that starts to remove the references to Early Access. 

The next task (and majority of the work) is to update 
https://github.com/googlefonts/japanese/blob/davelab6-no-ea/src/data/fonts.json with the new CSS urls to make use of the fonts.

I suggest making a PR from `davelab6-no-ea` to `master`, to review all the changes.

Finally, when merged, rebuild the site (`npm run build`) and push the output into the [gh-pages](https://github.com/googlefonts/japanese/tree/gh-pages) branch in order to go live.

**Comment by rsheeter** [comment]
`grep -R -P '(Early Access|/earlyaccess|日本語 早期アクセス)'` from root

**Comment by rsheeter** [comment]
The urls should be very simple: you have the google_fonts_id, use it and request /css? google_fonts_id.replace(' ', '').

I think updating the rest of the site to make sense is going to be the real work.
