### ISSUE TITLE
linkのrel要素について

### ISSUE THREAD

**Issue by SnO2WMaN** [googlefonts/japanese#4]
`<link href="https://fonts.googleapis.com/earlyaccess/mplus1p.css" />`
          
`<link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/mplus1p.css" />`

https://googlefonts.github.io/japanese/
サイト内の全てのHTMLリンクタグにrel要素が付いていません。

**Comment by davelab6** [comment]
Thank you!! 🎉
