### ISSUE TITLE
Missing Rel Element of Link Tag

### ISSUE THREAD

**Issue by SnO2WMaN** [googlefonts/japanese#6]
https://googlefonts.github.io/japanese/

Example
`<link href="https://fonts.googleapis.com/earlyaccess/mplus1p.css" />`
missing `rel="stylesheet"`.

Please add it.
`<link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/mplus1p.css" />`

Sorry I'm Japanese so I can't use english very well...

**Comment by kennethormandy** [comment]
Thanks very much for pointing this out, it is fixed now. Your English is great!

**Comment by SnO2WMaN** [comment]
Thank you very much! ^w^
