### ISSUE TITLE
Issues with combining characters in Kokoro

### ISSUE THREAD

**Issue by kennethormandy** [googlefonts/japanese#7]
Via @pomax, thanks for the heads up. https://twitter.com/TheRealPomax/status/788626714989584384

![therealpomax_2016-oct-18](https://cloud.githubusercontent.com/assets/1581276/19530751/f874e69e-95e9-11e6-9cf9-c67b587ca801.jpg)

**Comment by mandel59** [comment]
![2](https://cloud.githubusercontent.com/assets/1079715/19547958/6487f03c-96d6-11e6-869b-56b0d20b1a9c.PNG)
(captured with Firefox on Windows 10)
The voiced sound mark in 「カフェでコーヒ」 is decomposed too.

**Comment by SnO2WMaN** [comment]
Right in Japanese "カフェでコーヒー"(Please add "ー")

**Comment by Pomax** [comment]
for further details, I encountered this in Firefox 49 on Windows 10, although there have also been reports of the dakuten not combining in Firefox 49 on Linux.

**Comment by davelab6** [comment]
Seems there are still things to do based on the the above discussion...

**Comment by kennethormandy** [comment]
Mariko and I just had a call and got to the bottom of this! There were a few things written out as their base character + the diacritic mark rather than the single character with both. (ex. `し` + ` ゙` instead of `じ`. Apparently the former format works fine in Chrome and Safari but not Firefox, so Mariko helped me change it to the single-character versions.

This is resolved in the NicoMoji and Kokoro sections now, and these changes have both been deployed. Thanks for the help with this everyone!

**Comment by Pomax** [comment]
nice!
