### ISSUE TITLE
Incorrect weight on M+ fonts 

### ISSUE THREAD

**Issue by mandel59** [googlefonts/japanese#8]
![mplus](https://cloud.githubusercontent.com/assets/1079715/19548179/d9a95f58-96d7-11e6-95cc-8fd46046c638.PNG)
The "Thin", "Heavy" and "Black" glyphs are actually rendered with Light, Bold and Heavy fonts.

**Comment by kennethormandy** [comment]
Thanks, great catch. This has been fixed. I’ve also corrected the name Heavy to Extra Bold now, which is what’s being used in the production CSS.

@davelab6, is the Thin version intentionally set with the `font-weight` of `250` in [the CSS](https://fonts.googleapis.com/earlyaccess/mplus1p.css) or could it be `200`? I know this is going to be an option in the future, but right now it’s treated as an error so I don’t think this style is actually accessible.

**Comment by davelab6** [comment]
CSS is 200, the internal metadata value is 250

**Comment by davelab6** [comment]
Fixed

<img width="1227" alt="screen shot 2016-11-09 at 12 18 51" src="https://cloud.githubusercontent.com/assets/261579/20147590/b4ea1ea6-a676-11e6-8dfc-12ffb8256ac4.png">
