### ISSUE TITLE
Font-Family

### ISSUE THREAD

**Issue by SnO2WMaN** [googlefonts/japanese#9]
https://googlefonts.github.io/japanese/

On Website
`.wf-mplus1p {font-family: "M+ 1p"; }`

But On CSS
`.wf-mplus1p {font-family: "Mplus 1p"; }`

And M+ Rounded,Hannary Mincho
Please Check CSS...

**Comment by kennethormandy** [comment]
Thanks very much, good catch! This fix has been deployed.
